#!/bin/bash
export TMPDIR=/lscratch/$SLURM_JOB_ID
module load R/4.2
Rscript /home/perofskyamc/SFS_Rt_Block_Bootstrap/CCF_COVID_Rt_vs_mobility_epidemia_block_bootstrap_5mo_window_Biowulf_masking_exp_decay.R > Rtry_biowulf_covid_block_bootstrap_masking_exp_decay.out